# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-03 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20181127_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_range',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
