# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20181203_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age_range',
            field=models.CharField(choices=[(b'under_18', 'under 18'), (b'18_24', '18-24'), (b'25_34', '25-34'), (b'35_50', '35-50'), (b'over_50', 'over 50'), (b'none', 'Prefer not to say')], default=b'none', max_length=50),
        ),
    ]
